Resources:
  bedrockbucket363DEAB0:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: br-agent-bucket7cb96892-e1ae-4bd7-897d-5f8b729d21c9
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: br-agent/bedrock_bucket/Resource
  bucketnameparam9D880E65:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /br_agent/bucket_name
      Type: String
      Value: br-agent-bucket7cb96892-e1ae-4bd7-897d-5f8b729d21c9
    Metadata:
      aws:cdk:path: br-agent/bucket_name_param/Resource
  sqlitedbnameDF19802A:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /br_agent/sqlite_db_name
      Type: String
      Value: database/pets.db
    Metadata:
      aws:cdk:path: br-agent/sqlite_db_name/Resource
  dynamotable3CD87A3A:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /br_agent/dynamo_table
      Type: String
      Value: BreedInfoForPetStore
    Metadata:
      aws:cdk:path: br-agent/dynamo_table/Resource
  petstoreonline0AAA5DEA:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /br_agent/petstore_online_url
      Type: String
      Value: https://petstore.swagger.io/v2/pet/findByStatus?status=available
    Metadata:
      aws:cdk:path: br-agent/pet_store_online/Resource
  lambdarole3F9471F6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: lambda_role for br_agent actions
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonS3FullAccess
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonSSMFullAccess
    Metadata:
      aws:cdk:path: br-agent/lambda_role/Resource
  bedrockrole634D9AD9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
        Version: "2012-10-17"
      Description: lambda_role for setup
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AWSLambda_FullAccess
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonS3FullAccess
    Metadata:
      aws:cdk:path: br-agent/bedrock_role/Resource
  lambdasetup8AD6EBAC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 8a8e0c9282f1a0889821e53423723ff350bca0fff327066fc6b09bb47580d586.zip
      Handler: lambda_setup.lambda_handler
      Role:
        Fn::GetAtt:
          - lambdarole3F9471F6
          - Arn
      Runtime: python3.9
      Timeout: 300
    DependsOn:
      - lambdarole3F9471F6
    Metadata:
      aws:cdk:path: br-agent/lambda_setup/Resource
      aws:asset:path: asset.8a8e0c9282f1a0889821e53423723ff350bca0fff327066fc6b09bb47580d586
      aws:asset:is-bundled: false
      aws:asset:property: Code
  lambdasqlite95216148:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 8a8e0c9282f1a0889821e53423723ff350bca0fff327066fc6b09bb47580d586.zip
      Handler: lambda_sqlite.lambda_handler
      Role:
        Fn::GetAtt:
          - lambdarole3F9471F6
          - Arn
      Runtime: python3.9
      Timeout: 300
    DependsOn:
      - lambdarole3F9471F6
    Metadata:
      aws:cdk:path: br-agent/lambda_sqlite/Resource
      aws:asset:path: asset.8a8e0c9282f1a0889821e53423723ff350bca0fff327066fc6b09bb47580d586
      aws:asset:is-bundled: false
      aws:asset:property: Code
  lambdadynamoD9ABC851:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 8a8e0c9282f1a0889821e53423723ff350bca0fff327066fc6b09bb47580d586.zip
      Handler: lambda_dynamo.lambda_handler
      Role:
        Fn::GetAtt:
          - lambdarole3F9471F6
          - Arn
      Runtime: python3.9
      Timeout: 300
    DependsOn:
      - lambdarole3F9471F6
    Metadata:
      aws:cdk:path: br-agent/lambda_dynamo/Resource
      aws:asset:path: asset.8a8e0c9282f1a0889821e53423723ff350bca0fff327066fc6b09bb47580d586
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/z1O0Q6CMAz8Ft5HJRITfRQSnwl+ACmj4oRtyTpiDOHf3UB8uuvd9dojXDLIEnxzKrshHVUL892jHESQmplzmItJDuRF+TA/tkGBTItg1nHBKdNX6FCTJxej/2ERCkOktiNFPeIiRtRthzDfJiO9siY6Ow+deYPM5BmuERZRE9vJSRLrHN7rw7m1bTcCL63p1FZQffzTmkMOZzglL1YqdZPxShPUG34BkaEo0PYAAAA=
    Metadata:
      aws:cdk:path: br-agent/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

